Repository callstack/rspress-theme, pull requests merged in 2025-07, with the labels that each got.

#14 fix: edit on github
  packages/tester/rspress.config.ts
  packages/theme/src/assets/edit-box.svg
  packages/theme/src/styles/styles.css
Labels: release: bug fix

#15 feat: VersionBadge component
  packages/tester/theme/index.tsx
  packages/theme/src/theme/components/index.ts
  packages/theme/src/theme/components/version-badge/index.tsx
Labels: release: feature

#18 fix: add `noSSR` for announcement component
  packages/theme/src/theme/components/announcement/index.tsx
Labels: release: bug fix

#21 fix: use withBase from runtime
  packages/theme/src/theme/components/home-hero/index.tsx
Labels: release: bug fix

#24 feat: support links in `HomeFeature` component
  packages/theme/src/theme/components/home-feature/index.tsx
Labels: release: feature

#25 fix: multiple styling issues
  packages/theme/src/assets/noise.svg
  packages/theme/src/styles/styles.css
  packages/theme/src/theme/components/home-hero/index.module.scss
Labels: release: bug fix

#26 feat: LinkCard component
  packages/tester/docs/test/extra.mdx
  packages/tester/theme/index.tsx
  packages/theme/README.md
  packages/theme/src/theme/components/index.ts
  packages/theme/src/theme/components/link-card/arrow-right.svg
  packages/theme/src/theme/components/link-card/index.module.scss
  packages/theme/src/theme/components/link-card/index.tsx
Labels: release: feature

#29 fix: landing unclickable elements
  packages/theme/src/styles/styles.css
Labels: release: bug fix

#32 docs: update template of theme entrypoint to re-export LinkCard and other customized components
  packages/theme/README.md
Labels: documentation

#33 feat: turn on button hover animation only on fine pointers (not touch devices)
  packages/theme/src/theme/components/button/index.module.scss
Labels: release: feature

#31 fix: remove fixed height style for HomeHero container
  packages/theme/src/theme/components/home-hero/index.module.scss
Labels: release: bug fix

#36 fix: hero spacing and constrained height
  packages/theme/src/theme/components/home-hero/index.module.scss
Labels: enhancement, release: bug fix

#41 docs: update font to `block` to avoid FOUT
  packages/theme/README.md
Labels: release: bug fix

#43 fix: button background edge case
  packages/theme/src/theme/components/button/index.module.scss
Labels: release: bug fix

#45 feat: automate installation of theme
  packages/tester/theme/assets/alert.svg
  packages/tester/theme/assets/arrow-down.svg
  packages/tester/theme/assets/arrow-right.svg
  packages/tester/theme/assets/callstack.svg
  packages/tester/theme/assets/check-double.svg
  packages/tester/theme/assets/close.svg
  packages/tester/theme/assets/details.svg
  packages/tester/theme/assets/empty.svg
  packages/tester/theme/assets/hero-bg-shape.svg
  packages/tester/theme/assets/info-box.svg
  packages/tester/theme/assets/menu.svg
  packages/tester/theme/assets/moon.svg
  packages/tester/theme/assets/noise.svg
  packages/tester/theme/assets/notes.svg
  packages/tester/theme/assets/search.svg
  packages/tester/theme/assets/small-menu.svg
  packages/tester/theme/assets/sun.svg
  packages/tester/theme/assets/warning-box.svg
  packages/tester/theme/index.tsx
  packages/theme/README.md
  packages/theme/cli.cjs
  packages/theme/package.json
  packages/theme/rslib.config.ts
  packages/theme/src/plugin/index.ts
  packages/theme/src/plugin/theme.ts
  packages/theme/src/theme/components/home-footer/index.module.scss
  packages/theme/tsconfig.json
  packages/theme/tsconfig.plugin.json
Labels: release: feature

#44 feat: hover animations for theme & social buttons
  packages/tester/rspress.config.ts
  packages/tester/theme/assets/edit-box.svg
  packages/theme/src/plugin/theme.ts
  packages/theme/src/styles/styles.css
  packages/theme/src/theme/components/index.ts
  packages/theme/src/theme/components/switch-appearance/index.module.scss
  packages/theme/src/theme/components/switch-appearance/index.tsx
  packages/theme/src/theme/components/switch-appearance/moon.svg
  packages/theme/src/theme/components/switch-appearance/sun.svg
Labels: release: feature

#47 feat: allow customizing outline cta
  packages/theme/src/theme/components/outline-cta/index.tsx
  packages/theme/src/theme/const.ts
Labels: release: feature

#48 feat: customize home banner
  packages/theme/src/theme/components/home-banner/index.module.scss
  packages/theme/src/theme/components/home-banner/index.tsx
  packages/theme/src/theme/const.ts
Labels: release: feature

#51 fix: font rendering in buttons
  packages/theme/src/theme/components/button/index.module.scss
Labels: release: bug fix

#55 feat: themed card component
  packages/tester/docs/test/extra.mdx
  packages/theme/src/plugin/theme.ts
  packages/theme/src/theme/components/card/index.module.scss
  packages/theme/src/theme/components/card/index.tsx
  packages/theme/src/theme/components/index.ts
Labels: release: feature

#56 feat: themed badge component
  packages/tester/docs/test/extra.mdx
  packages/theme/src/plugin/theme.ts
  packages/theme/src/styles/styles.css
  packages/theme/src/theme/components/badge/index.module.scss
  packages/theme/src/theme/components/badge/index.tsx
  packages/theme/src/theme/components/index.ts
Labels: release: feature

#57 fix: landing header & letter-spacing
  packages/tester/docs/test/extra.mdx
  packages/theme/src/styles/styles.css
  packages/theme/src/theme/components/home-hero/index.module.scss
Labels: release: bug fix
